/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  subm:  ControllerPanTilt
 *  model: ControllerPanTilt
 *  expmt: 20-E9D4
 *  date:  April 7, 2023
 *  time:  10:14:43 AM
 *  user:  20-sim 5.0 Student License
 *  from:  Universiteit Twente
 *  build: 5.0.2.12127
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/


